# Generated by Django 4.1.1 on 2023-01-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickerApp', '0002_shoplist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='ShopImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
