# Generated by Django 4.1.1 on 2023-01-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickerApp', '0005_user_auth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
    ]
