# Generated by Django 4.1.1 on 2023-01-19 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickerApp', '0009_rename_fullname_user_first_name_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
