# Generated by Django 4.1.1 on 2023-01-19 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickerApp', '0010_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
    ]
